FROM node:iron
RUN npm install -g pnpm
COPY . /usr/src/app
WORKDIR /usr/src/app
SHELL ["/bin/bash", "--login", "-c"]
ENV SHELL bash
# RUN chmod 777 /usr/src/app -R
RUN echo Y | pnpm install
CMD ["pnpm", "dev"]
