services:
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ricochet
      MYSQL_PASSWORD: ricochet
      MYSQL_USER: ricochet
      MYSQL_DATABASE: ricochet
    volumes:
      - mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_PORT=3306
      - PMA_HOST=mysql
      - PMA_USER=ricochet
      - PMA_PASSWORD=ricochet
  prod:
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - "./.env"
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
  ws-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.ws_dev
    ports:
      - "3001:3001"
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
volumes:
  mysql: ~
  dev:
