import type { GridType } from "~/shared/grid";

export const defaultGrid: GridType = [
  [
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: true, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: true, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
  ],
  [
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: true, wallY: true, type: "red_cog" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
  ],
  [
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: true, wallY: true, type: "yellow_moon" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
  ],
  [
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: true, wallY: false, type: "blue_cog" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: true, wallY: false, type: "blue_star" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
  ],
  [
    { wallX: false, wallY: true, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: true, type: "red_planet" },
    { wallX: true, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: true, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: true, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "green_moon" },
    { wallX: true, wallY: false, type: "empty" },
  ],
  [
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "green_star" },
    { wallX: true, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: true, type: "yellow_planet" },
    { wallX: true, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: true, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
  ],
  [
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: true, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
  ],
  [
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: true, wallY: true, type: "empty" },
    { wallX: false, wallY: true, type: "empty" },
    { wallX: true, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
  ],
  [
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: true, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: true, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: true, type: "empty" },
  ],
  [
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: true, type: "yellow_star" },
    { wallX: true, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: true, type: "empty" },
    { wallX: false, wallY: true, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: true, wallY: true, type: "red_star" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
  ],
  [
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: true, wallY: true, type: "joker" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
  ],
  [
    { wallX: false, wallY: false, type: "empty" },
    { wallX: true, wallY: false, type: "red_moon" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "green_planet" },
    { wallX: true, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
  ],
  [
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: true, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "blue_planet" },
    { wallX: true, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: true, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
  ],
  [
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: true, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: true, type: "yellow_cog" },
    { wallX: true, wallY: false, type: "empty" },
  ],
  [
    { wallX: false, wallY: true, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: true, wallY: true, type: "green_cog" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: true, type: "blue_moon" },
    { wallX: true, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
  ],
  [
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: true, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: true, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
    { wallX: false, wallY: false, type: "empty" },
  ],
];
